% (C) Copyright 2022 Remi Gau

cwd = fileparts(mfilename('fullpath'));
addpath(fullfile(cwd, 'lib', 'bidspm'));
bidspm init;

bids_dir = fullfile(cwd, '..', 'inputs', 'ds003717');
output_dir = fullfile(cwd, '..', 'outputs');

bidspm(bids_dir, output_dir, 'subject', ...
       'action', 'create_roi', ...
       'participant_label', {'01'}, ...
       'verbosity', 2, ...
       'roi_atlas', 'wang', ...
       'roi_name', {'V1v', 'V1d'}, ...
       'space', {'IXI549Space', 'individual'}, ...
       'preproc_dir', preproc_dir);

participants = {'01', '02'};

preproc_dir = fullfile(output_dir, 'derivatives', 'bidspm-preproc');
roi_dir = fullfile(output_dir, 'derivatives', 'bidspm-roi');

model_file = fullfile(cwd, 'models', 'model-defaultSESS01_smdl.json');

bidspm(bids_dir, output_dir, 'subject', ...
       'action', 'results', ...
       'preproc_dir', preproc_dir, ...
       'model_file', model_file, ...
       'participant_label', participants, ...
       'verbosity', 2, ...
       'roi_based', true, ...
       'roi_name', {'V1v', 'V1d'}, ...
       'space', {'individual'}, ...
       'roi_dir', roi_dir, ...
       'design_only', false, ...
       'concatenate', false, ...
       'fwhm', 6, ...
       'skip_validation', true);
