%% smooth
bidspm(fmriprep_dir, output_dir, 'subject', 'action', 'smooth', ...
       'task', {'Motion'}, 'space', {'MNI152NLin6Asym'}, 'fwhm', 6);

%% stat
bidspm(bids_dir, output_dir, 'subject', 'action', 'stats', ...
       'preproc_dir', preproc_dir, 'model_file', model_file, ...
       'fwhm', 6);

bidspm(bids_dir, output_dir, 'dataset', 'action', 'stats', ...
       'preproc_dir', preproc_dir, 'model_file', model_file, ...
       'fwhm', 6);
