function test_suite = test_bidsCopyRawFolder %#ok<*STOUT>
    try % assignment of 'localfunctions' is necessary in Matlab >= 2016
        test_functions = localfunctions(); %#ok<*NASGU>
    catch % no problem; early Matlab versions can use initTestSuite fine
    end
    initTestSuite;
end

function test_bidsCopyRawFolderBasic()

    % directory with this script becomes the current directory
    opt.dataDir = fullfile( ...
                           fileparts(mfilename('fullpath')), ...
                           '..', 'demos',  'MoAE', 'output', 'MoAEpilot');

    % group of subjects to analyze
    opt.groups = {''};
    % suject to run in each group
    opt.subjects = {[]};
    % task to analyze
    opt.taskName = 'auditory';

    checkDependencies();
    opt = checkOptions(opt);

    bidsCopyRawFolder(opt, 1);

    assertEqual(exist( ...
                      fullfile(opt.dataDir, '..', ...
                               'derivatives', 'SPM12_CPPL', ...
                               'dataset_description.json'), 'file'), ...
                2);

    assertEqual(exist( ...
                      fullfile(opt.dataDir, '..', ...
                               'derivatives', 'SPM12_CPPL', 'sub-01', 'func', ...
                               'sub-01_task-auditory_bold.nii'), 'file'), ...
                2);

    assertEqual(exist( ...
                      fullfile(opt.dataDir, '..', ...
                               'derivatives', 'SPM12_CPPL', 'sub-01', 'anat', ...
                               'sub-01_T1w.nii'), 'file'), ...
                2);
end
