% (C) Copyright 2023 bidspm developers

clear;
clc;

addpath(fullfile(pwd, '..', '..'));
bidspm();

participant_label = {'01'};
TASK = 'linebisection';

root_dir = fileparts(mfilename('fullpath'));
bids_dir = fullfile(root_dir, 'inputs', 'ds000114');
output_dir = fullfile(root_dir, 'outputs', 'ds000114', 'derivatives');
preproc = fullfile(output_dir, 'bidspm-preproc');

bidspm(bids_dir, output_dir, 'subject', ...
       'participant_label', participant_label, ...
       'action', 'copy', ...
       'task', TASK, ...
       'skip_validation', true, ...
       'verbosity', 3);

bids_filter_file = struct( ...
                          'bold', struct('modality', 'func', 'suffix', 'bold', 'ses', 'retest'), ...
                          't1w',  struct('modality', 'anat', 'suffix', 'T1w'));
bidspm(bids_dir, output_dir, 'subject', ...
       'participant_label', participant_label, ...
       'action', 'preprocess', ...
       'task', TASK, ...
       'space', {'IXI549Space'}, ...
       'skip_validation', true, ...
       'ignore', {'slicetiming', 'unwarp'}, ...
       'bids_filter_file', bids_filter_file, ...
       'fwhm', 6, ...
       'verbosity', 3);
