%  Show how to use filter to only include one session to preprocess.

% (C) Copyright 2023 bidspm developers

clear;
clc;

addpath(fullfile(pwd, '..', '..'));
bidspm();

participant_label = {'04', '05'};
TASK = 'linebisection';
session_to_select = {'test', 'retest'};

root_dir = fileparts(mfilename('fullpath'));
bids_dir = fullfile(root_dir, 'inputs', 'ds000114');
output_dir = fullfile(root_dir, 'outputs', 'ds000114', 'derivatives');
preproc = fullfile(output_dir, 'bidspm-preproc');

%% Copy
% To make sure we still have copied all the data
% bidspm(bids_dir, output_dir, 'subject', ...
%        'participant_label', participant_label, ...
%        'action', 'copy', ...
%        'skip_validation', true, ...
%        'verbosity', 3);

%% Set filter and preprocess
bids_filter_file = struct('bold', struct('modality', 'func', ...
                                         'suffix', 'bold', ...
                                         'ses',  {session_to_select}), ...
                          't1w',  struct('modality', 'anat', ...
                                         'suffix', 'T1w'));
bidspm(bids_dir, output_dir, 'subject', ...
       'participant_label', participant_label, ...
       'action', 'preprocess', ...
       'task', TASK, ...
       'space', {'IXI549Space'}, ...
       'skip_validation', true, ...
       'ignore', {'slicetiming', 'unwarp'}, ...
       'bids_filter_file', bids_filter_file, ...
       'fwhm', 6, ...
       'verbosity', 3);
