% (C) Copyright 2021 CPP_SPM developers

function test_suite = test_spm_2_bids_cpp %#ok<*STOUT>
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_spm_2_bids_cpp_spm_mapping()

  opt = setOptions('vismotion');

  opt = set_spm_2_bids_defaults(opt);

  anatFile = 'sub-01_T1w.nii';

  funcFile = 'sub-01_task-auditory_bold.nii';

  pfx_in_out = {'wc1', anatFile, 'sub-01_space-IXI549Space_res-bold_label-GM_probseg.nii'; ...
                'wc2', anatFile, 'sub-01_space-IXI549Space_res-bold_label-WM_probseg.nii'; ...
                'wc3', anatFile, 'sub-01_space-IXI549Space_res-bold_label-CSF_probseg.nii'; ...
                {'s6u', 's6r', 's6ua', 's6ra'},  ...
                funcFile, 'sub-01_task-auditory_space-individual_desc-smth6_bold.nii'; ...
                {'s6wu', 's6wr', 's6wua', 's6wra'},  ...
                funcFile, 'sub-01_task-auditory_space-IXI549Space_desc-smth6_bold.nii'; ...
                's6',  funcFile, 'sub-01_task-auditory_desc-smth6_bold.nii'; ...
                'rc1', anatFile, 'sub-01_space-individual_res-bold_label-GM_probseg.nii'; ...
                'rc2', anatFile, 'sub-01_space-individual_res-bold_label-WM_probseg.nii'; ...
                'rc3', anatFile, 'sub-01_space-individual_res-bold_label-CSF_probseg.nii'; ...
                'rp_', funcFile, 'rp_sub-01_task-auditory_bold.nii'; ...
                'rp_a', funcFile, 'rp_asub-01_task-auditory_bold.nii'; ...
                'wm', anatFile, 'sub-01_space-IXI549Space_res-hi_T1w.nii'; ...
                {'u', 'ua'}, funcFile, ...
                'sub-01_task-auditory_space-individual_desc-preproc_bold.nii'; ...
                'wm', ...
                'sub-01_desc-skullstripped_T1w.nii', ...
                'sub-01_space-IXI549Space_res-hi_desc-preproc_T1w.nii'; ...
                {'m'}, ... % cover case w/out prefix
                'sub-01_desc-skullstripped_T1w.nii', ... % TODO cover case w/ space specified
                'sub-01_space-individual_desc-preproc_T1w.nii'; ...
                {'m'}, ...
                'sub-01_space-individual_desc-something_label-brain_mask.nii', ...
                'sub-01_space-individual_label-brain_mask.nii'; ...
                {'std_u', 'std_ua'}, funcFile, ...
                'sub-01_task-auditory_space-individual_desc-std_bold.nii'; ...
                {'c1'}, 'sub-01_T1w.surf.gii', ...
                'sub-01_desc-pialsurf_T1w.gii'; ...
                {'w'}, 'sub-01_desc-skullstripped_T1w.nii', ...
                'sub-01_space-individual_res-hi_desc-preproc_T1w.nii' ...
               };

  for i = 1:size(pfx_in_out, 1)

    prefixes = get_prefixes(pfx_in_out, i);

    for j = 1:numel(prefixes)

      file = [prefixes{j} pfx_in_out{i, 2}];

      filename = spm_2_bids(file, opt);

      msg = sprintf('%s --> %s\n', file, filename);
      printToScreen(msg, opt);

      expected = pfx_in_out{i, 3};
      assertEqual(filename, expected);

    end
  end

end

function prefixes = get_prefixes(prefix_and_output, row)
  prefixes = prefix_and_output{row, 1};
  if ~iscell(prefixes)
    prefixes = {prefixes};
  end
end
