# Final output
cpp_spm-preproc/sub-01/func/: 	sub-01_task-auditory_desc-confounds_regressors.tsv \
								sub-01_task-audio_desc-stc_bold.mat \
								sub-01_task-auditory_label-bold_unwarpparam.mat \
								sub-01_task-audio_space-IXI549Space_desc-mean_bold.nii \
								sub-01_task-audio_space-IXI549Space_desc-preproc_bold.nii \
								sub-01_task-audio_space-T1w_desc-mean_bold.nii \
								sub-01_task-audio_space-T1w_desc-preproc_bold.nii

cpp_spm-preproc/sub-01/anat/: 	sub-01_space-individual_label-GM_probseg.nii \
								sub-01_space-individual_label-WM_probseg.nii \
								sub-01_space-individual_label-CSF_probseg.nii \
								sub-01_from-IXI549Space_to-T1w_mode-image_xfm.nii \
								sub-01_space-individual_label-brain_mask.nii \
								sub-01_space-individual_desc-skullstripped_T1w.nii \
								sub-01_space-individual_desc-biascor_T1w.nii \
								sub-01_space-IXI549Space_res-r1pt0_desc-preproc_T1w.nii \
								sub-01_space-IXI549Space_res-bold_label-GM_probseg.nii \
								sub-01_space-IXI549Space_res-bold_label-WM_probseg.nii \
								sub-01_space-IXI549Space_res-bold_label-CSF_probseg.nii


# Realign and unwarp
usub-01_task-audio_desc-stc_bold.nii: sub-01_task-audio_desc-stc_bold.nii 

meansub-01_task-audio_desc-stc_bold.nii: sub-01_task-audio_desc-stc_bold.nii 

rp_sub-01_task-audio_desc-stc_bold.nii: sub-01_task-audio_desc-stc_bold.nii 

sub-01_task-auditory_label-bold_unwarpparam.mat: sub-01_task-audio_desc-stc_bold.nii 

# Segmentation
msub-01_T1w.nii: sub-01_T1w.nii

c1sub-01_T1w.nii: sub-01_T1w.nii

c2sub-01_T1w.nii: sub-01_T1w.nii

c3sub-01_T1w.nii: sub-01_T1w.nii

sub-01_label-T1w_segparam: sub-01_T1w.nii

ysub-01_T1w.nii: sub-01_T1w.nii

iysub-01_T1w.nii: sub-01_T1w.nii


# Skullstripping
sub-01_space-individual_desc-skullstripped_T1w.nii: msub-01_T1w.nii \
													c1sub-01_T1w.nii \
													c2sub-01_T1w.nii \
													c3sub-01_T1w.nii

sub-01_space-individual_label-brain_mask.nii: c1sub-01_T1w.nii c2sub-01_T1w.nii c3sub-01_T1w.nii

# Coregister
usub-01_task-audio_space-T1w_desc-stc_bold.nii: meansub-01_task-audio_desc-stc_bold.nii msub-01_T1w.nii
												

meansub-01_task-audio_space-T1w_desc-stc_bold.nii: 	meansub-01_task-audio_desc-stc_bold.nii msub-01_T1w.nii
														

sub-01_task-audio_desc-stc_bold.mat: 	meansub-01_task-audio_desc-stc_bold.nii msub-01_T1w.nii
										

# Normalize
wmeansub-01_task-audio_desc-stc_bold.nii: meansub-01_task-audio_desc-stc_bold.nii ysub-01_T1w.nii 

wusub-01_task-audio_desc-stc_bold.nii: usub-01_task-audio_desc-stc_bold.nii ysub-01_T1w.nii 

wmsub-01_T1w.nii: msub-01_T1w.nii ysub-01_T1w.nii 

wc1sub-01_T1w.nii: c1sub-01_T1w.nii ysub-01_T1w.nii 

wc2sub-01_T1w.nii: c2sub-01_T1w.nii ysub-01_T1w.nii 

wc3sub-01_T1w.nii: c3sub-01_T1w.nii ysub-01_T1w.nii 


# Rename

sub-01_task-auditory_desc-confounds_regressors.tsv: rp_sub-01_task-audio_desc-stc_bold.nii 

sub-01_space-individual_desc-biascor_T1w.nii: msub-01_T1w.nii

sub-01_space-individual_label-GM_probseg.nii: c1sub-01_T1w.nii

sub-01_space-individual_label-WM_probseg.nii: c2sub-01_T1w.nii

sub-01_space-individual_label-CSF_probseg.nii: c3sub-01_T1w.nii

sub-01_space-IXI549Space_res-r1pt0_desc-preproc_T1w.nii: wmsub-01_T1w.nii

sub-01_space-IXI549Space_res-bold_label-GM_probseg.nii: wc1sub-01_T1w.nii

sub-01_space-IXI549Space_res-bold_label-WM_probseg.nii: wc2sub-01_T1w.nii

sub-01_space-IXI549Space_res-bold_label-CSF_probseg.nii: wc3sub-01_T1w.nii

sub-01_from-IXI549Space_to-T1w_mode-image_xfm.nii: iysub-01_T1w.nii

sub-01_from-T1w_to-IXI549Space_mode-image_xfm.nii: ysub-01_T1w.nii

sub-01_task-audio_space-IXI549Space_desc-mean_bold.nii: wmeansub-01_task-audio_desc-stc_bold.nii 

sub-01_task-audio_space-IXI549Space_desc-preproc_bold.nii: wusub-01_task-audio_desc-stc_bold.nii 

sub-01_task-audio_space-T1w_desc-mean_bold.nii: meansub-01_task-audio_space-T1w_desc-stc_bold.nii 

sub-01_task-audio_space-T1w_desc-preproc_bold.nii: usub-01_task-audio_space-T1w_desc-stc_bold.nii 