function test_suite = test_bidspm_copy_raw %#ok<*STOUT>

  % (C) Copyright 2023 bidspm developers

  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_copy_anat_only()

  inputPath = fullfile(getMoaeDir(), 'inputs', 'raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'anat_only', true, ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 1);

end

function test_copy_no_task()

  inputPath = fullfile(getMoaeDir(), 'inputs', 'raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 3);

end

function test_copy_filter_suffix()

  inputPath = fullfile(getMoaeDir(), 'inputs', 'raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'bids_filter_file', struct('bold', struct('modality', 'func', ...
                                                   'suffix', 'events')), ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 1);

end

function test_copy_filter_session()

  inputPath = getTestDataDir('raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'participant_label', {'01', 'ctrl01'}, ...
         'task', {'vismotion'}, ...
         'bids_filter_file', struct('bold', struct('modality', 'func', ...
                                                   'suffix', 'events', ...
                                                   'ses', '01')), ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 8);

end

function test_copy_filter_anat()

  inputPath = getTestDataDir('raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'participant_label', {'01', 'ctrl01'}, ...
         'task', {'vismotion'}, ...
         'bids_filter_file', struct('anat', struct('modality', 'anat', ...
                                                   'suffix', 'T1w', ...
                                                   'ses', '01')), ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 2);

end

function test_copy_several_filter()

  inputPath = getTestDataDir('raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'participant_label', {'01', 'ctrl01'}, ...
         'task', {'vismotion'}, ...
         'bids_filter_file', struct('anat', struct('modality', 'anat', ...
                                                   'suffix', 'T1w', ...
                                                   'ses', '01'), ...
                                    'bold', struct('modality', 'func', ...
                                                   'suffix', 'events', ...
                                                   'ses', '01')), ...
         'verbosity', 0);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false);

  assertEqual(numel(bids.query(BIDS, 'data')), 10);

end
