function test_suite = test_bidspm_smooth %#ok<*STOUT>

  % (C) Copyright 2023 bidspm developers

  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end

  initTestSuite;

end

function test_smooth()

  inputPath = fullfile(getMoaeDir(), 'inputs', 'fmriprep');

  outputPath = tmpName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'smooth', ...
         'task', {'auditory'}, ...
         'space', {'MNI152NLin6Asym'}, ...
         'fwhm', 6, ...
         'verbosity', 0, ...
         'dry_run', true);

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'smooth', ...
         'task', {'auditory'}, ...
         'space', {'MNI152NLin6Asym'}, ...
         'fwhm', 6, ...
         'verbosity', 0, ...
         'dry_run', false);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false, ...
                     'index_dependencies', false);

  assertEqual(numel(bids.query(BIDS, 'data', 'desc', 'smth6')), 2);

end

function test_smooth_anat_only()

  inputPath = fullfile(getMoaeDir(), 'inputs', 'fmriprep');

  outputPath = tmpName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'smooth', ...
         'task', {'auditory'}, ...
         'space', {'MNI152NLin6Asym'}, ...
         'fwhm', 6, ...
         'verbosity', 0, ...
         'dry_run', true);

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'smooth', ...
         'task', {'auditory'}, ...
         'space', {'MNI152NLin6Asym'}, ...
         'fwhm', 6, ...
         'verbosity', 0, ...
         'dry_run', false);

  BIDS = bids.layout(fullfile(outputPath, 'derivatives', 'bidspm-preproc'), ...
                     'verbose', false, ...
                     'use_schema', false, ...
                     'index_dependencies', false);

  assertEqual(numel(bids.query(BIDS, 'data', 'desc', 'smth6')), 2);

end

function pth = tmpName()
  pth = tempname();
  mkdir(pth);
end
