function test_suite = test_bidspm_boilderplate %#ok<*STOUT>

  % (C) Copyright 2023 bidspm developers

  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end

  initTestSuite;

end

function test_boilerplate_create_roi_only()

  %   if ~bids.internal.is_github_ci()
  %     moxunit_throw_test_skipped_exception(['When not in CI the octache partials ', ...
  %                                           'are not in the right place']);
  %   end

  outputPath = tmpName();

  bidspm(pwd, outputPath, ...
         'subject', ...
         'action', 'create_roi', ...
         'boilerplate_only', true, ...
         'roi_atlas', 'glasser', ...
         'roi_name', {'OFC'}, ...
         'space', {'IXI549Space'}, ...
         'verbosity', 0);

  cleanUp(fullfile(pwd, 'options'));
  cleanUp(fullfile(pwd, 'error_logs'));

  assertEqual(exist(fullfile(outputPath, ...
                             'derivatives', ...
                             'bidspm-roi', ...
                             'reports', ...
                             'create_roi_atlas-glasser_citation.md'), ...
                    'file'), ...
              2);

end

function test_boilerplate_stats_only()
  %
  %   if ~bids.internal.is_github_ci()
  %     moxunit_throw_test_skipped_exception(['When not in CI the octache partials ', ...
  %                                           'are not in the right place']);
  %   end

  outputPath = tmpName();

  opt = setOptions('MoAE');

  spm_mkdir(opt.dir.preproc);

  for i_roi_based = 0:1

    roi_based = true;
    if i_roi_based == 0
      roi_based = false;
    end

    bidspm(opt.dir.raw, outputPath, 'subject', ...
           'action', 'stats', ...
           'preproc_dir', opt.dir.preproc, ...
           'model_file',  opt.model.file, ...
           'boilerplate_only', true, ...
           'roi_based', roi_based, ...
           'verbosity', 0, ...
           'fwhm', 6);

    assertEqual(exist(fullfile(outputPath, ...
                               'derivatives', ...
                               'bidspm-stats', ...
                               'reports', ...
                               'stats_model-auditory_citation.md'), ...
                      'file'), ...
                2);

  end

end

function test_boilerplate_preproc_only()

  %   if ~bids.internal.is_github_ci()
  %     moxunit_throw_test_skipped_exception(['When not in CI the octache partials ', ...
  %                                           'are not in the right place']);
  %   end

  outputPath = tmpName();

  opt = setOptions('MoAE');

  bidspm(opt.dir.raw, outputPath, 'subject', ...
         'action', 'preprocess', ...
         'boilerplate_only', true, ...
         'task', {'auditory'}, ...
         'verbosity', 0, ...
         'fwhm', 6);

  assertEqual(exist(fullfile(outputPath, ...
                             'derivatives', ...
                             'bidspm-preproc', ...
                             'reports', ...
                             'preprocess_citation.md'), ...
                    'file'), ...
              2);
end

function pth = tmpName()
  pth = tempname();
  mkdir(pth);
end
