function value = lowLevelActions()
  % (C) Copyright 2022 bidspm developers
  value = {'init'; ...
           'uninit'; ...
           'dev'
           'version'; ...
           'run_tests'; ...
           'update'; ...
           'help'; ...
           'meaning_of_life'};
end
