---
name: Bug report

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to report a bug

title: '[BUG]'

labels: ['bug :bug:']

body:

- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

      To maximize chances for a quick fix make sure you know
      [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Operating system
    description: What operating system are you using?
    options:
    - label: Linux
    - label: Mac
    - label: Windows

- type: textarea
  attributes:
    label: Operating system version
    value: |
      - Linux Ubuntu 22.04 "jammy jellyfish"
      - Mac OS Version 12 "monterey"
  validations:
    required: false

- type: checkboxes
  attributes:
    label: SPM 12 version
    description: "What SPM 12 version are you using?\nType `spm('version')` into the MATLAB / Octave command line to know."
    options:
    - label: '7771'
    - label: '7487'
    - label: '7219'

- type: checkboxes
  attributes:
    label: Platform
    description: Which platform and version are you running?
    options:
    - label: MATLAB
    - label: Octave

- type: textarea
  attributes:
    label: Platform version
    value: |
      - MATLAB 2017a
      - Octave 4.2.2

- type: dropdown
  attributes:
    label: bidspm version
    description: |
      In the MATLAB / Octave command line, try one of the following:

       - `bidspm version`
       - `bidspm('version')`
       - `getVersion`

      Or check the content of CITATION.cff.
    options:
    - v3.0.0
    - v2.3.0
    - v2.2.0
    - v2.1.0
    - v2.0.0
    - v1.1.5
    - v1.1.4
    - v1.1.3
    - v1.1.2
    - v1.1.1
    - v1.1.0
    - v1.0.0
    - v0.2.0
    - v0.1.0
    - v0.0.3
    - v0.0.2
    - v0.0.1
  validations:
    required: true

- type: textarea
  attributes:
    label: bidspm branch / commit number
    description: |
      In a terminal:

       - `git rev-parse --abbrev-ref HEAD`
       - `git rev-parse --short HEAD`

      In the MATLAB command line

       - `[branch, commit] = getRepoInfo()`
    placeholder: |
      - main 29b689dd
      - dev 1bda0162

- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe what outcome you expected.
    placeholder: Describe what outcome you expected.
  validations:
    required: false

- type: textarea
  attributes:
    label: BIDS stats model
    description: If your error is related to running GLMs with bidspm, it may be useful to share your BIDS stats model.
    render: json
    placeholder: Paste your BIDS stats model here.
  validations:
    required: false

- type: textarea
  attributes:
    label: Current Behavior & Error message
    description: |
      Describe what you got instead.
      If possible paste below the error message you encountered.
      Also add the error.log that might have been generated.
    value: |
      ```matlab
      % copy the error you got below
      % before the three backticks (```)




      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
