function test_suite = test_renameNidm %#ok<*STOUT>
  % (C) Copyright 2023 bidspm developers
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_renameNidm_basic()

  glmDir = tempname();
  spm_mkdir(glmDir);
  outputFile = 'spm_0001.nidm.zip';
  fid = fopen(fullfile(glmDir, outputFile), 'w');
  fclose(fid);

  opt = struct('taskName', {{'MGT'}});

  subLabel = '01';

  result = struct('MC', 'FWE', ...
                  'atlas', 'Neuromorphometrics', ...
                  'binary', 0, ...
                  'csv', 1, ...
                  'k', 0, ...
                  'name', 'cash_demean_3', ...
                  'nidm', 1, ...
                  'nodeName', 'run_level', ...
                  'p', 0.0500, ...
                  'png', 1, ...
                  'threshSpm', 0, ...
                  'useMask', 0, ...
                  'space', {{'MNI152NLin2009cAsym'}}, ...
                  'dir', glmDir);

  renameNidm(opt, result, subLabel);

  renamedFile =  ['sub-01_task-MGT_space-MNI152NLin2009cAsym_label-0001', ...
                  '_desc-cashDemean3_p-0pt050_k-0_MC-FWE_nidm.zip'];

  assertEqual(exist(fullfile(glmDir, renamedFile), 'file'), 2);

end

function test_renameNidm_group()

  glmDir = tempname();
  spm_mkdir(glmDir);
  outputFile = 'spm_0001.nidm.zip';
  fid = fopen(fullfile(glmDir, outputFile), 'w');
  fclose(fid);

  opt = struct('taskName', {{'MGT'}});

  result = struct('MC', 'FWE', ...
                  'atlas', 'Neuromorphometrics', ...
                  'binary', 0, ...
                  'csv', 1, ...
                  'k', 0, ...
                  'name', 'cash_demean_3', ...
                  'nidm', 1, ...
                  'nodeName', 'run_level', ...
                  'p', 0.0500, ...
                  'png', 1, ...
                  'threshSpm', 0, ...
                  'useMask', 0, ...
                  'space', {{'MNI152NLin2009cAsym'}}, ...
                  'dir', glmDir);

  renameNidm(opt, result);

  renamedFile =  ['task-MGT_space-MNI152NLin2009cAsym_label-0001', ...
                  '_desc-cashDemean3_p-0pt050_k-0_MC-FWE_nidm.zip'];

  assertEqual(exist(fullfile(glmDir, renamedFile), 'file'), 2);

end
