% (C) Copyright 2020 CPP BIDS SPM-pipeline developers

function content = createEmptytModelBasic()
  %
  % Creates the content of a basic model.json file for GLM analysis with some default options
  % like high pass filter cut-off and the type of autocorrelation correction
  %
  % USAGE::
  %
  %   content = createEmptytModelBasic()
  %
  % :returns:
  %
  % - :content: structure containing the output that can be saved with
  %             ``spm_jsonwrite()``
  %
    
    

  content.Name = ' ';
  content.Description = ' ';
  content.Input = struct('task', ' ');
  content.Steps = { ...
                   struct( ...
                          'Level', 'subject', ...
                          'Transformations', { ...
                                              {struct( ...
                                                      'Name', 'Factor', ...
                                                      'Inputs', {{'trial_type'}} ...
                                                     ); ...
                                               struct( ...
                                                      'Name', 'Convolve', ...
                                                      'Model', 'spm', ...
                                                      'Inputs', {{' '}} ...
                                                     )}
                                             }, ...
                          'Model', struct( ...
                                          'X', {{' '}}, ...
                                          'Options', ...
                                          struct('high_pass_filter_cutoff_secs', 128), ...
                                          'Software', ...
                                          struct('SPM', struct('whitening', 'FAST')), ...
                                          'Mask', {' '}), ...
                          'AutoContrasts', {{' '}}); ...
                   struct( ...
                          'Level', 'run', ...
                          'AutoContrasts', {{' '}} ...
                         ); ...
                   struct( ...
                          'Level', 'dataset', ...
                          'AutoContrasts', {{' '}} ...
                         ) ...
                  };

end
