function contrasts  = defaultContrastsStructure()
  %
  % (C) Copyright 2022 CPP_SPM developers

  contrasts =  struct('nodeName', '', ...
                      'name', {{''}}, ...
                      'useMask', false(), ...
                      'MC', 'FWE', ... % FWE, none, FDR
                      'p', 0.05, ...
                      'k', 0);

end
