% (C) Copyright 2019 CPP BIDS SPM-pipeline developers

function results  = returnDefaultResultsStructure()

  Contrasts =  struct( ...
                      'Name', '', ...
                      'useMask', false(), ...
                      'MC', 'FWE', ... % FWE, none, FDR
                      'p', 0.05, ...
                      'k', 0);

  Output = struct( ...
                  'png', false(), ...
                  'csv', false(), ...
                  'thresh_spm', false(), ...
                  'binary', false(), ...
                  'montage', struct( ...
                                    'do', false(), ...
                                    'slices', [], ...
                                    'orientation', 'axial', ...
                                    'background',  fullfile(spm('dir'), ...
                                                            'canonical', ...
                                                            'avg152T1.nii,1')), ...
                  'NIDM_results', false());

  results = struct( ...
                   'Level',  '', ...
                   'Contrasts', Contrasts, ...
                   'Output', Output);

end
