% (C) Copyright 2019 CPP BIDS SPM-pipeline developers


function results  = returnDefaultResultsStructureBasic()
    
    Contrasts =  struct( ...
        'Name', '', ...
        'useMask', false(), ...
        'MC', 'FWE', ... % FWE, none, FDR
        'p', 0.05, ...
        'k', 0);
    
    Output = struct(...
        'png', false(), ...
        'csv', false(), ...
        'thresh_spm', false(), ...
        'montage', false(), ...
        'NIDM_results', false());
    
    results = struct( ...
        'Level',  '', ... 
        'Contrasts', Contrasts, ...
        'Output', Output);
    
end