---
title: "bidspm an SPM centric BIDS app"
author:
  - name: Rémi Gau
    orcid: 0000-0002-1535-9767
    affiliation: 1
  - name: Marco Barilari
    orcid: 0000-0002-3313-3120
    affiliation: 1
  - name: Ceren Battal
    orcid: 0000-0002-9844-7630
    affiliation: 1
  - name: Jeanne Caron-Guyon
    orcid: 0000-0001-8681-5267
    affiliation: 1
  - name: Filippo Cerpelloni
    orcid: 0000-0001-8070-5753
    affiliation: 1
  - name: Federica Falagiarda
    orcid: 0000-0001-7844-1605
    affiliation: 1
  - name: Ane Gurtubay
    orcid: 0000-0003-3824-2219
    affiliation: 1
  - name: Michèle MacLean
    orcid: 0000-0002-0174-9326
    affiliation: 2
  - name: Stefania Mattioni
    orcid: 0000-0001-8279-6118
    affiliation: 3
  - name: Mohamed Rezk
    orcid: 0000-0002-1866-8645
    affiliation: 1
  - name: Iqra Shahzad
    orcid: 0000-0002-8724-7668
    affiliation: 1
  - name: Ying Yang
    orcid: 0000-0002-4157-2975
    affiliation: 1
  - name: Olivier Collignon
    orcid: 0000-0003-1882-3550
    affiliation: 1
affiliations:
  - name: |
      Institute for research in Psychology (IPSY) & Neuroscience (IoNS), Louvain Bionics, Crossmodal Perception and Plasticity Laboratory - University of Louvain (UCLouvain), Louvain, Belgium.
    index: 1
  - name: Département de psychologie, Université de Montréal, Montréal, Canada
    index: 2
  - name: Experimental Psychology, Ghent University, Ghent, Belgium
    index: 3
  - name: Brain and cognition, Leuven Brain Institute, KU Leuven, Belgium
    index: 4
date: "2022-12-17"
output:
  word_document: default
  pdf_document: default
bibliography: OHBM_2023.bib
---

# Abstract

## Introduction

Great strides have recently been made in standardizing the format of
neuroimaging data with initiatives such as the Brain Imaging Data Structure
(@bids) and pipelines like fmriprep (@fmriprep). However, the statistical
analysis phase of the typical neuroimaging process requires a significant amount
of flexibility, which often leads to non-reproducible and heterogeneous scripts.
Additionally, scientific publications often lack critical contextual
information, making it hard to replicate the analyses from published studies.
Even when analysis scripts are shared, they may lack transparency, making it
difficult to understand and apply the same model to different datasets.

To address these issues, the
[BIDS Statistical Model](https://bids-standard.github.io/stats-models/) was
recently developed to promote automated model fitting pipelines (see for example
[fitlins](https://github.com/poldracklab/fitlins)). However, there is no
integration of the BIDS statistical model with SPM12. bidSPM is a BIDS app to
fill this gap and make it easier to leverage this new tool.

## Methods

The philosophy of bidSPM is to take standardized data and configuration files as
input and to return standardized outputs. This should minimize how much code
researchers have to write.

bidSPM uses the BIDS app CLI (@bids_app) to provide a standardized way to run
fMRI analysis of a BIDS dataset with SPM12 and several of its complementary
toolboxes. Analyses can be done at the subject and group level, on the whole
brain or in a region of interest. Additionally, the bidspm pipeline can be a
preparatory step for different kinds of analyses, whether task-free
(resting-state) or task-based univariate and multivariate studies.

To run a statistical analysis, bidSPM only requires as inputs:

- a valid raw BIDS dataset
- its BIDS derivatives (preprocessed by fmriprep or by bidSPM itself)
- a bids stats model JSON file.

The BIDS stats model is used to define the input data, the variables and the
confound variables to include in the general linear model (GLM), the contrasts
to estimates as well as several options for HRF convolution, model estimation,
results to display…

Having a single JavaScript Object Notation (JSON) file to define one analysis
allows researchers to easily create several models. bidSPM can then help choose
the best model as it can perform bayesian model selection via the model
assessment, comparison and selection (MACS) toolbox (@macs) of SPM12.

This feature can be relevant to compare 1) different cognitive models for a
given task, 2) denoising strategies. This approach provides a principled way to
choose a model for a given dataset without having to peek at the results, and
thus may also help prevent procedural over-fitting (@choosing).

## Results

In the end bidSPM outputs follow the BIDS derivatives conventions and GLM
results are stored in a NIDM results (@nidm_results) allowing researchers to
upload their results to [Neurovault](https://neurovault.org/), (@neurovault) in
a couple of clicks.

Additionally, bidSPM can easily provide 4D maps of a subject’s GLM output (beta
/ t-maps) to allow further analysis using MVPA classification frameworks or RSA
tools, making it a bridge connecting different frameworks.

## Conclusion

bidSPM provides researchers with a flexible way to run statistical analysis
using SPM12 with a single JSON file and only a few lines of code based on data
formatted in BIDS.

bidSPM can be run on MATLAB or Octave and is also packaged as docker image and
is available on [github](https://github.com/cpp-lln-lab/bidspm) and
[dockerhub](https://hub.docker.com/repository/docker/cpplab/bidspm/).

We hope that this tool will make it easier for the community to adopt practices
that lead to more reproducible results by relying on standardised pipelines that
are easily shareable.

## References
