% (C) Copyright 2020 CPP_SPM developers

function test_suite = test_setBatchComputeVDM %#ok<*STOUT>
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_setBatchComputeVDM_basic()

  fmapType = 'phasediff';
  refImage = fullfile(pwd, 'mean_sub-01-task-rest_bold.nii');

  matlabbatch = {};
  matlabbatch = setBatchComputeVDM(matlabbatch, fmapType, refImage);

  expectedBatch = returnExpectedBatch(refImage);

  assertEqual(matlabbatch, expectedBatch);

end

function expectedBatch = returnExpectedBatch(refImage)

  expectedBatch = [];

  expectedBatch{end + 1}.spm.tools.fieldmap.calculatevdm.subj(1).data.presubphasemag.phase = '';
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).data.presubphasemag.magnitude = '';

  UF = struct( ...
              'method', 'Mark3D', ...
              'fwhm', 10, ...
              'pad', 0, ...
              'ws', 1);

  MF = struct( ...
              'fwhm', 5, ...
              'nerode', 2, ...
              'ndilate', 4, ...
              'thresh', 0.5, ...
              'reg', 0.02);

  defaultsval = struct( ...
                       'et', [NaN NaN], ...
                       'maskbrain', 1, ...
                       'blipdir', 1, ...
                       'tert', '', ...
                       'epifm', 0, ... % can be changed
                       'ajm', 0, ...
                       'uflags', UF, ...
                       'mflags', MF);

  defaultsval.mflags.template = { spm_select( ...
                                             'FPList', ...
                                             fullfile( ...
                                                      spm('dir'), ...
                                                      'toolbox', ...
                                                      'FieldMap'), ...
                                             '^T1.nii$')};

  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).defaults.defaultsval = defaultsval;

  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).session.epi = {refImage};
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).matchvdm = 1;
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).sessname = 'vdm-';
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).writeunwarped = 1;
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).anat = '';
  expectedBatch{end}.spm.tools.fieldmap.calculatevdm.subj(1).matchanat = 0;

end
