function ffxDir = getFFX_MVPA_dir(subNumber, degreeOfSmoothing, opt)
ffxDir = fullfile(opt.derivativesDir,...
    ['sub-',subNumber],...
    ['stats'],...
    ['ffx_',opt.taskName],...
    ['ffx_MVPA_',num2str(degreeOfSmoothing)']);

if ~exist(ffxDir,'dir')
    mkdir(ffxDir)
end
end