function renamePng(directory)
  %
  % removes the _XXX suffix before the PNG extension in files generated by SPM
  % in a directory
  %
  % USAGE::
  %
  %     renamePng(directory)
  %
  %
  % (C) Copyright 2021 CPP_SPM developers

  pngFiles = spm_select('FPList', directory, '^sub-.*[0-9].png$');

  for iFile = 1:size(pngFiles, 1)
    source = deblank(pngFiles(iFile, :));
    basename = spm_file(source, 'basename');
    target = spm_file(source, 'basename', basename(1:end - 4));
    movefile(source, target);
  end

end
