% (C) Copyright 2021 CPP_SPM developers

clear;
clc;

run ../../initCppSpm.m;

%% --- parameters

subLabel = 'pilot001';

use_schema = false;

%% --- run

opt = high_res_get_option();

derivatives = bids.layout(opt.derivativesDir, use_schema);

MP2RAGE = bids.query(derivatives, 'data', ...
                     'sub', subLabel, ...
                     'suffix', 'UNIT1', ...
                     'acq', 'lores', ...
                     'extension', '.nii');

other = bids.query(derivatives, 'data', ...
                   'sub', subLabel, ...
                   'suffix', 'MP2RAGE', ...
                   'acq', 'lores', ...
                   'extension', '.nii');

T1w = bids.query(derivatives, 'data', ...
                 'sub', subLabel, ...
                 'suffix', 'T1w', ...
                 'prefix', 'm', ...
                 'extension', '.nii');

%% coregisterMp2rageToT1w
matlabbatch = {};
matlabbatch = setBatchCoregistration(matlabbatch, T1w{1}, MP2RAGE{1}, other);
batchName = 'coregisterMp2rageToT1w';
saveAndRunWorkflow(matlabbatch, batchName, opt, subLabel);

%% coregisterVasoToT1w
% and also bold and fake T1

task = 'gratingBimodalMotion';
mean_bold = bids.query(derivatives, 'data', ...
                       'sub', subLabel, ...
                       'task', task, ...
                       'prefix', 'mean', ...
                       'suffix', 'bold', ...
                       'extension', '.nii');

mean_vaso = bids.query(derivatives, 'data', ...
                       'sub', subLabel, ...
                       'task', task, ...
                       'prefix', 'mean', ...
                       'suffix', 'vaso', ...
                       'extension', '.nii');

other = bids.query(derivatives, 'data', ...
                   'sub', subLabel, ...
                   'task', task, ...
                   'prefix', 'moco_', ...
                   'extension', '.nii');

other = cat(1, other, mean_vaso);

matlabbatch = {};
matlabbatch = setBatchCoregistration(matlabbatch, T1w{1}, mean_bold{1}, other);
batchName = 'coregisterVasoToT1w';
saveAndRunWorkflow(matlabbatch, batchName, opt, subLabel);

exit;
