function model = createEmptyModel()
  %
  % (C) Copyright 2020 CPP_SPM developers

  model = struct( ...
                 'X', {{' '}}, ...
                 'HRF', struct('Variables', {{''}}, ...
                               'Model', 'DoubleGamma'), ...
                 'Type', 'glm', ...
                 'Options', struct('HighPassFilterCutoffHz', 0.0078, 'Mask', ''), ...
                 'Software', struct('SPM', struct('SerialCorrelation', 'FAST', ...
                                                  'HRFderivatives', 'Temporal')));
end
