function transformation = createEmptyTransformation()
  %
  % (C) Copyright 2020 CPP_SPM developers

  transformation =   {struct( ...
                             'Name', 'Factor', ...
                             'Inputs', {{'trial_type'}} ...
                            ); ...
                      struct( ...
                             'Name', 'Convolve', ...
                             'Model', 'spm', ...
                             'Inputs', {{' '}} ...
                            )};

end
