function node = createEmptyNode(level)
  %
  % (C) Copyright 2020 CPP_SPM developers

  node =  struct( ...
                 'Level', level, ...
                 'Name', [level '_level'], ...
                 'Transformations', {createEmptyTransformation()}, ...
                 'Model', createEmptyModel(), ...
                 'Contrasts', struct('Name', '',...
                                          'ConditionList', {{''}}, ...
                                          'Weights', {{''}}, ...
                                          'Test', ''), ...
                 'DummyContrasts',  struct('Test', '', ...
                                            'Contrasts', {{''}}));
end
