function model = createEmptyModel()
  %
  % (C) Copyright 2020 CPP_SPM developers

  model = struct( ...
                 'X', {{' '}}, ...
                 'Options', struct('high_pass_filter_cutoff_secs', 128), ...
                 'Software', struct('SPM', struct('whitening', 'FAST')), ...
                 'Mask', {' '});
end
