function printProcessingRun(groupName, iSub, subID, iSes, iRun)

    fprintf(1, ...
        [ ...
        'PROCESSING GROUP: %s' ...
        'SUBJECT No.: %i ' ...
        'SUBJECT ID : %s ' ...
        'SESSION: %i ' ...
        'RUN:  %i \n'], ...
        groupName, iSub, subID, iSes, iRun);

end
