function fileName = get_filename(BIDS, subNumber, session, run, type, opt)

fileName = spm_BIDS(BIDS, 'data', ...
    'sub', subNumber, ...
    'run', run, ...
    'ses', session, ...
    'task', opt.taskName, ...
    'type', type);

end