function [runs, numRuns] = get_runs(BIDS, subNumber, session, opt)
runs = spm_BIDS(BIDS, 'runs', ...
    'sub', subNumber, ...
    'task', opt.taskName, ...
    'ses', session, ...
    'type', 'bold');
numRuns = size(runs,2);     % Get the number of runs

end