---
name: apptainer build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                submodules: recursive
                fetch-depth: 0

        -   uses: eWaterCycle/setup-apptainer@v2
            with:
                apptainer-version: 1.3.0
        -   name: build sif image
            run: apptainer build bidspm.sif bidspm.def
        -   name: version
            run: apptainer run bidspm.sif --version
