name: Changelog

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:

  node-docker:

    runs-on: ubuntu-latest
    container:
      image: ferrarimarco/github-changelog-generator:1.14.3

    steps:
      - uses: actions/checkout@v2

      - name: Run changelog builder
        run: if (git log -1 --pretty=%s | grep Merge*) && (! git log -1 --pretty=%b | grep REL:) ; then

              github_changelog_generator --user cpp-lln-lab --project CPP-SPM --token ${CHANGE_TOKEN} \
              --output ~/build/CHANGES.md --base ~/build/src/pregh-changes.md --header-label "# Changelog" \
              --no-issues --no-issues-wo-labels --no-filter-by-milestone --no-compare-link --pr-label "" --release-branch master

              cat ~/build/CHANGES.md

              mv ~/build/CHANGES.md ~/build/doc/CHANGES.md

             else

              echo "Commit or Release, do nothing"

             fi
