---
name: issues
on:
  issues:
    types: [opened]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Install FAQtory
      run: pip install FAQtory
    - name: Run Suggest
      env:
        TITLE: ${{ github.event.issue.title }}
      run: faqtory suggest "$TITLE" > suggest.md
    - name: Read suggest.md
      id: suggest
      uses: juliangruber/read-file-action@v1
      with:
        path: ./suggest.md
    - name: Suggest FAQ
      uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: ${{ steps.suggest.outputs.content }}
