---
name: FAQtory issues

on:

  issues:
    types: [opened]

jobs:
  add-comment:

    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:

    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Install FAQtory
      run: pip install FAQtory

    - name: Run Suggest
      run: faqtory suggest "${{ github.event.issue.title }}" > suggest.md

    - name: Read suggest.md
      id: suggest
      uses: juliangruber/read-file-action@v1
      with:
        path: ./suggest.md

    - name: Suggest FAQ
      uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b
      with:
        issue-number: ${{ github.event.issue.number }}
        body: ${{ steps.suggest.outputs.content }}
